# ===========================
# Server
# ===========================
server.port=8080

# ===========================
# Database
# ===========================
spring.datasource.url=jdbc:postgresql://localhost:5432/commercehub_db
spring.datasource.username=postgres
spring.datasource.password=postgres

# ===========================
# JPA
# ===========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===========================
# JWT
# ===========================
jwt.secret=MzQ1Njc4OTAxMjM0NTY3ODkwMTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM=
jwt.expiration=86400000
# ===========================
# Cloudinary
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}